
# Custom CSS configuration

# How to use?
# From within a controller or view access variables using one
# of the following styles:
#
#  In css.yml:
#
#  common: &common
#    foo: "1px"
#
#   reset:
#    <<: *common
#    bar: "stuff"
    
#
#  In a VIEW:
# 
#  <%= CssReset.foo %>
#  <%= CssGrid.page_width %>

########
# NOTE : Webserver RESTART is required to see changes to this file!
########

common: &common
  
  # common MUST always have at least one value set!  Do not remove! Bug?
  foo: "bar"
  
reset:
  <<: *common

grid:
  <<: *common
  
  # default page width in pixels
  page_width: 950
  
  # default number of columns (Integer)
  number_of_columns: 24
  
  # column width in pixels
  column_width: 30
  
  # margin width in pixels
  margin_width: 10
  
  form_action: '/generate/grid'
  

typography:
  <<: *common

grid_png:
  <<: *common
  # the background color of the image (hex value)
  background_color: '#FFFFF'
  
  # the colour of the grid part in the image (hex value)
  grid_color: '#F3F5F7'
  
  # the colour of the baseline (hex value)
  baseline_color: '#E6E6EC'
  